<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><UserSecretsId>smtp-email-service-development</UserSecretsId></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SmtpEmailService.Application\SmtpEmailService.Application.csproj" />
    <ProjectReference Include="..\SmtpEmailService.Infrastructure\SmtpEmailService.Infrastructure.csproj" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>
</Project>
